export const IPC_CHANNELS = {
    log: {
        write: "log:write",
        export: "log:export",
    },
    window: {
        minimize: "window:minimize",
        switchSize: "window:switchSize",
        close: "window:close",
        setRect: "window:setRect",
        setIgnoreMouseEvents: "window:setIgnoreMouseEvents",
        setAlwaysOnTop: "window:setAlwaysOnTop",
    },
    setting: {
        load: "setting:load",
        save: "setting:save",
        export: "setting:export",
        import: "setting:import",
        windowColorLoad: "window_color:load",
        windowColorSave: "window_color:save",
        windowColorPresetsLoad: "window_color_presets:load",
        windowColorPresetsSave: "window_color_presets:save",
    },
    project: {
        saveAs: "project:saveAs",
        save: "project:save",
        load: "project:load",
        loadFromPath: "project:loadFromPath",
        pickSavePath: "project:pickSavePath",
        materializeCacheImages: "project:materializeCacheImages",
    },
    scene: {
        loadFromPath: "scene:loadFromPath",
    },
    imageSettingsWindow: {
        toggle: "imageSettingsWindow:toggle",
        loadImage: "image:load",
        getImageInfo: "image:getInfo",
        pasteImage: "imageSettingsWindow:pasteImage",
        saveCacheImageAs: "imageSettingsWindow:saveCacheImageAs",
    },
    dimensionSettingsWindow: {
        toggle: "dimensionSettingsWindow:toggle",
    },
    sync: {
        updateImageSets: "imageSets:update",
        updateDimensionLines: "dimensionLines:update",
        updateUnitFactor: "unitFactor:update",
        updateUnit: "unit:update",
        updateInteractionMode: "interactionMode:update",
        updateSelectedImageId: "selectedImageId:update",
        updateSelectedDimensionLineId: "selectedDimensionLineId:update",
        updateProjectDirty: "project:dirty:update",
        requestInitialState: "state:requestInitial",
    },
    license: {
        get: "license:get",
        appVersion: "app:getVersion",
    },
    capture: {
        screen: "capture-screen",
        window: "capture-window",
        saveImageData: "save-image-data",
    },
    e2e: {
        getStatus: "e2e:getStatus",
        setSceneFromPath: "e2e:setSceneFromPath",
        loadFixtureImage: "e2e:loadFixtureImage",
        waitStable: "e2e:waitStable",
        capture: "e2e:capture",
    },
} as const;

export const IPC_EVENTS = {
    imageSetsUpdated: "imageSets:updated",
    dimensionLinesUpdated: "dimensionLines:updated",
    unitFactorUpdated: "unitFactor:updated",
    unitUpdated: "unit:updated",
    interactionModeUpdated: "interactionMode:updated",
    selectedImageIdUpdated: "selectedImageId:updated",
    selectedDimensionLineIdUpdated: "selectedDimensionLineId:updated",
    languageUpdated: "language:updated",
    alwaysOnTopShortcutTriggered: "alwaysOnTop:shortcutTriggered",
    clickThroughShortcutTriggered: "clickThrough:shortcutTriggered",
    requestStateSync: "state:requestSync",
    fileOpen: "file:open",
} as const;
